name: ci
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
jobs:
  publish-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id_token: write
    strategy:
      matrix:
        #python-version: ["3.8", "3.9", "3.10", "3.11"]
        python-version: ["3.10"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.0.3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      #- name: Login to Docker Hub
      #  uses: docker/login-action@v2
      #  with:
      #    username: ${{ secrets.DOCKERHUB_USERNAME }}
      #    password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: docker_meta
        uses: docker/metadata-action@v3.6.0
        with:
          images: ghcr.io/MatthiasValvekens/uwsgi-minimal
          tags: |
            type=sha,format=long            
            type=raw,latest-py${{ matrix.python-version }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: src
          #platforms: linux/amd64,linux/arm/v7,linux/arm64
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
      - name: Sign images using GHA OIDC identity
        run: cosign sign --yes ${TAGS}
        env:
          TAGS: ${{ steps.docker_meta.outputs.tags }}
