name: Publish release
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
jobs:
  publish-images:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.0.3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: docker_meta
        uses: docker/metadata-action@v4.4.0
        with:
          images: |
            mfjval/uwsgi-minimal
            ghcr.io/MatthiasValvekens/uwsgi-minimal
          flavor: |
            latest=false
            suffix=-py${{ matrix.python-version }},onlatest=${{ matrix.python-version != '3.11' }}
          tags: |
            type=sha,format=long,priority=200
            type=semver,pattern={{version}},event=tag,priority=800
            type=semver,pattern={{major}}.{{minor}},event=tag,priority=700
            type=raw,value=unstable,enable={{is_default_branch}},priority=400
            type=raw,value=latest,event=tag,priority=900
            type=raw,value=latest,enable=${{ matrix.python-version == '3.11' && startsWith(github.ref, 'refs/tags/') }},suffix=,event=tag,priority=1000
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: src
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
      - name: Sign images using GHA OIDC identity
        run: cosign sign --yes ${TAGS}
        env:
          TAGS: ${{ steps.docker_meta.outputs.tags }}
